Update cli.sh
Qitmeer/qng pull request #322
Opened 2022-12-24 14:42 UTC by blocklee

The old usage `block <order|hash>` may be misleading. The result of `cli.sh block $hash` is `null`,  only can get the block by the command `cli.sh blockbyhash $hash`.

2022-12-26 03:24 UTC, lochjin requested changes
I just tested that the call of this command was OK. I was wondering if you didn't have a hex prefix `0x`

2022-12-27 01:45 UTC, dindinw commented
@blocklee
following are **all the working examples**, the `block` command support both order and hash as input arguments. 
```
./cli.sh block 120 
./cli.sh block 0x4595a9a8a924e3c799a0b54555c2f2ff8fdcad15c8fd3b0f413450831d2174a1
./cli.sh blockbyhash 4595a9a8a924e3c799a0b54555c2f2ff8fdcad15c8fd3b0f413450831d2174a1
./cli.sh blockbyhash 0x4595a9a8a924e3c799a0b54555c2f2ff8fdcad15c8fd3b0f413450831d2174a1
```
but **without adding `0x` prefix** when calling the `block` command results an error, (using `-D` to see the error message)
```
./cli.sh block 4595a9a8a924e3c799a0b54555c2f2ff8fdcad15c8fd3b0f413450831d2174a1
{"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid character 'a' after array element"}}
```
Please refactoring your PR.

2022-12-27 07:40 UTC, dindinw approved these changes

2022-12-27 07:46 UTC, lochjin approved these changes

2022-12-27 08:00 UTC, merged