Wallet modules
Qitmeer/qng pull request #353
Opened 2023-03-21 01:50 UTC by jamesvan2019

2023-03-21 09:13 UTC, lochjin requested changes

2023-03-21 09:13 UTC, lochjin commented on cmd/miner/symbols/lib/robot.go
> -					if err != ErrLimitWork { // limit wait block connect
Is there no need to add a frequency limit here?

2023-03-22 06:47 UTC, dindinw requested changes

2023-03-22 06:47 UTC, dindinw commented on node/full.go
> +func (qm *QitmeerFull) RegisterWalletService(cfg *config.Config, conf node.Config, _am *acct.AccountManager, _tm *tx.TxManager) error {
should not export the `github.com/ethereum/go-ethereum/node` here, from the `node.Config`
you might have to refactor the `wallet.New` API. and using the `go-ethereum` internally.

2023-09-08 02:49 UTC, frankcrypto2023 commented
move #522 https://github.com/Qitmeer/qng/pull/522

2023-09-08 02:49 UTC, closed without merging