mining stats
Qitmeer/qng pull request #399
Opened 2023-04-25 12:40 UTC by jamesvan2019

2023-04-26 23:19 UTC, lochjin approved these changes

2023-04-27 03:57 UTC, dindinw commented on services/miner/api.go
> +func (api *PublicMinerAPI) StatsGbtTxEmptyErr() {
should not let the method `Public` if it never has been called by the outside

2023-04-27 04:02 UTC, dindinw commented on services/miner/api.go
> +	api.stats.TxEmptyErrs++
the naming is not properly used, `NonTx` or `EmptyGbt` and It's not an error. it a status of the situation,  for example, using names like `statsEmptyGbt()` or` statsGbtNonTx()` maybe better.

2023-04-27 04:07 UTC, dindinw commented on services/miner/api.go
> +	LastGBTTime          time.Time `json:"last_gbt_time"`
`GBT` -> `Gbt`

2023-04-27 04:26 UTC, dindinw requested changes

2023-04-27 04:26 UTC, dindinw commented on services/miner/api.go
> +	LastSubmit           time.Time `json:"last_submit_time"`
`LatestGbtSubmit`

2023-04-27 04:26 UTC, dindinw commented on services/miner/api.go
> +	LastTxEmptyTime      int64     `json:"-"`
`LastTxEmptyTime` -> `LatestMempoolEmptyDuration`

2023-04-27 04:26 UTC, dindinw commented on services/miner/api.go
> +	TxEmptyAvgTime       float64   `json:"tx_empty_avg_time"`
`MempoolEmptyAvgDuration`

2023-04-27 04:26 UTC, dindinw commented on services/miner/api.go
> +	TxEmptyErrs          float64   `json:"tx_empty_errs"`
`MempoolEmptyWarns`

2023-04-27 04:26 UTC, dindinw commented on services/miner/api.go
> +	LastSubmit           time.Time `json:"last_submit_time"`
LastXXX -> LatestXXX

2023-04-28 04:49 UTC, dindinw requested changes

2023-04-28 04:49 UTC, dindinw commented on services/miner/miner.go
> +	LastestMempoolTxEmptyDuration   int64     `json:"-"`
`LastestMempoolTxEmptyDuration` -> `LastestMempoolEmptyDuration`
add new field `MaxMempoolEmptyDuration`

2023-04-28 04:49 UTC, dindinw commented on services/miner/miner.go
> +func (api *Miner) StatsEmptyGbt() {
fix all naming : `api` -> `miner`

2023-04-28 05:30 UTC, dindinw approved these changes

2023-04-28 05:30 UTC, merged