Optimize get block by evm number
Qitmeer/qng pull request #425
Opened 2023-05-13 14:45 UTC by lochjin

2023-05-13 22:17 UTC, dindinw requested changes
In general, It's okey for me to remove the `vmblockindex` entirely since the recent code refactoing.  but the search performance of the `evm_tx_id` -> `dag_tx_id` is very different than before cause the usage of the new added function `get_block_by_number`, which is implemented by searching the entire block dag using the binary search. 
I think the `evm <-> blockdag` index might be still required in the future.

2023-05-13 22:17 UTC, dindinw commented on core/blockchain/blockindex.go
> +func (b *BlockChain) GetBlockByNumber(number uint64) meerdag.IBlock {
code comments are required

2023-05-13 22:21 UTC, dindinw commented on services/tx/api.go
> +	b := api.txManager.GetChain().GetBlockByNumber(bid)
bid is a evm block number?

2023-05-14 01:06 UTC, lochjin commented on services/tx/api.go
> +	b := api.txManager.GetChain().GetBlockByNumber(bid)
Yes, this `bid` came from EVM API

2023-05-14 01:16 UTC, lochjin commented on core/blockchain/api.go
> +func (api *PublicBlockAPI) GetBlockByNumber(number uint64, verbose *bool, inclTx *bool, fullTx *bool) (interface{}, error) {
https://github.com/Qitmeer/qng/pull/425/commits/2a9ca35614056152e9eaec9b398721db71f5a88f

2023-05-14 01:16 UTC, lochjin commented on core/blockchain/blockindex.go
> +func (b *BlockChain) GetBlockByNumber(number uint64) meerdag.IBlock {
https://github.com/Qitmeer/qng/pull/425/commits/00aa08a77f110700cfc4f8ce28513fe3c514d27e

2023-05-14 01:18 UTC, lochjin commented
> In general, It's okey for me to remove the `vmblockindex` entirely since the recent code refactoing. but the search performance of the `evm_tx_id` -> `dag_tx_id` is very different than before cause the usage of the new added function `get_block_by_number`, which is implemented by searching the entire block dag using the binary search.
> I think the `evm <-> blockdag` index might be still required in the future.

Yes, the current implementation has performance bottlenecks. Future needs to be replaced with more efficient solutions

2023-05-14 06:53 UTC, merged