stats gbt2.0
Qitmeer/qng pull request #599
Opened 2024-01-25 10:51 UTC by frankcrypto2023

2024-01-28 08:07 UTC, dindinw approved these changes

2024-01-29 00:49 UTC, lochjin requested changes

2024-01-29 00:49 UTC, lochjin commented on params/params.go
> +	MinEmptyGbtDuration time.Duration
Will its purpose feel like it will affect `TargetTimePerBlock,` and will it make HashRate's calculation unrealistic

2024-01-29 03:27 UTC, lochjin approved these changes

2024-01-29 03:37 UTC, merged