change test to mock
Qitmeer/qng pull request #746
Opened 2024-08-12 17:51 UTC by frankcrypto2023

2024-08-12 23:39 UTC, lochjin requested changes

2024-08-12 23:39 UTC, lochjin commented on testutils/release_test.go
> +	GenerateBlockMockNode(t, h, 20)
https://github.com/Qitmeer/qng/blob/72a4ccb784bc0d228216c13edbc3772d0e363f8c/testutils/simulator/utils.go#L14

2024-08-12 23:39 UTC, lochjin commented on testutils/utils.go
> +func AssertBlockOrderAndHeightMockNode(t *testing.T, h *simulator.MockNode, order, total, height uint64) {
https://github.com/Qitmeer/qng/blob/72a4ccb784bc0d228216c13edbc3772d0e363f8c/testutils/simulator/utils.go#L33

2024-08-13 02:35 UTC, lochjin approved these changes

2024-08-13 02:35 UTC, dindinw approved these changes

2024-08-13 02:35 UTC, merged